### ISSUE TITLE
Liu-West resampling: Infinite error in covariance estimation

### ISSUE THREAD

**Issue by cgranade** [QInfer/python-qinfer#108]
When covariance matrices are dominated by uncertainty in a low-dimensional subspace, ``scipy.linalg.sqrtm`` can sometimes report infinite error even if ``n_ess`` is large. I suspect that this can be solved by replacing ``sqrtm`` with a eigendecomposition that uses the hermicity of the covariance matrix, but this should be tested for accuracy.

**Comment by ihincks** [comment]
I have run into this problem, too.

I seem to recall that SVD algorithms are generally more stable than eigendecomposition algorithms, but I can't find a solid source, just things like [the last page of these notes](http://cims.nyu.edu/~donev/Teaching/NMI-Fall2010/Lecture5.handout.pdf). I don't know if it matters in this context.
