### ISSUE TITLE
Domains Errors

### ISSUE THREAD

**Issue by whitewhim2718** [QInfer/python-qinfer#111]
Currently domains will fail as min/max values are by default set to `None` when bounds have not been set. This will cause various methods to fail either from attempting to cast a `None` type to `int` or comparing against a `None` type. This may be simply fixed by setting the bounds to `+-np.inf`

**Comment by ihincks** [comment]
Good catch. Out of curiosity, what's an example of a method that fails?

**Comment by whitewhim2718** [comment]
When running `test_concrete_models.py` over `BasicGaussianModel` the `in_domain` check will fail on simulated data as it will attempt to compare the generated data against a `None` min/max value as the domain is set to `RealDomain()`. Another case is for `BasicPoissonModel()` as the the max is `None` and `__init__` will try and cast `int(max)` which is equivalent to `int(None)` which fails.

**Comment by ihincks** [comment]
Fixed with #112
