### ISSUE TITLE
Coveralls not correctly linking to source files

### ISSUE THREAD

**Issue by cgranade** [QInfer/python-qinfer#120]
I suspect this is because we use ``src/qinfer`` instead of just ``qinfer``, but the metadata collected and analyzed by Coveralls is not correctly showing up on the website. For instance, in reporting on PR #119, Coveralls raises the error that [``qinfer/resamplers.py`` is not available](https://coveralls.io/jobs/24110166/source_files/755450351). This makes it difficult, to say the least, to determine why a coverage rate is affected by a particular PR.

**Comment by ihincks** [comment]
Was this fixed in #121?

**Comment by cgranade** [comment]
I think so, yes. I forgot to close the issue, sorry.
