### ISSUE TITLE
Feature: duecredit integration

### ISSUE THREAD

**Issue by cgranade** [QInfer/python-qinfer#128]
Since we now have a paper up on arXiv and Zenodo-issued DOIs, we may want to use [``duecredit``](https://github.com/duecredit/duecredit) to embed metadata for those citations. As a part of that, it might be worth filing a PR with ``duecredit`` itself to add injections for other dependencies. If we do decide to add ``duecredit`` annotations, we could possibly use their ``tags`` functionality to separate theory and implementation citations. Thoughts?

**Comment by ihincks** [comment]
This looks like a cool project and it seems to me like there are no downsides to using it. My pessimistic side wonders if it will actually work to the extent it deserves to work...

**Comment by cgranade** [comment]
Agreed on all counts. I'll prototype an implementation, then, if only to try and push things a little closer to working as well as they deserve to.

**Comment by ihincks** [comment]
Implemented in #129
