### ISSUE TITLE
Importing from qinfer.tests

### ISSUE THREAD

**Issue by ihincks** [QInfer/python-qinfer#131]
I want to do this:

    from qinfer.tests import test_model

But `qinfer.tests` is not in the `__init__`. This particular function (`test_model`) is meant to be used by users on custom models. Should it be moved, imported specially, or something else?

**Comment by dseuss** [comment]
BTW, this issue also kept me from creating a conda-forge package for qinfer.

**Comment by cgranade** [comment]
I think with #132 merged in, this issue can be closed now. Thanks!
