### ISSUE TITLE
Expose common functionality in qinfer/__init__.py.

### ISSUE THREAD

**Issue by cgranade** [QInfer/python-qinfer#14]
Currently, it takes several different ``import`` statements to pull in a reasonable subset of QInfer. The division into ``smc``, ``abstract_model``, etc. is useful in development and in disambiguating, but is rather useless to the user. Listing common functionality in ``qinfer/__init__.py`` should help with this, so that you can do something like the following:

```python
>>> import qinfer as qi
>>> model = qi.SimplePrecessionModel()
>>> prior = qi.UniformDistribution([0, 1])
>>> updater = qi.SMCUpdater(model, 1000, prior)
```

**Comment by scasagrande** [comment]
A few things I noticed while taking a look at this:

- The `__init__` file contains several `from file import *`, but not all. Should they all be there? For example, you can't do `qi.SMCUpdater` as per the issue text.
- `setup.py` does not have `scikit-learn` in `install_requires`, so it does not get installed when doing `pip install qinfer`

**Comment by cgranade** [comment]
The fix for ``__init__.py`` is currently in ``fix-cleanup`` (specifically 93bbe330f73419ab7225aea8c16e4cbce5655765). Once that gets merged in, I'll go on and close this issue accordingly. For the ``scikit-learn``, that's only needed for the clustering implementation which I'm in the process of reimplementing anyway--- as it turns out, sklearn has terrible support for weighted data.

**Comment by scasagrande** [comment]
Oh cool :+1: 

Maybe put the imports in `__init__.py` in alphabetical order to make it easier to look through?

And yeah, I only comment on the `scikit-learn` package because its in `requirements.txt`

**Comment by cgranade** [comment]
I think that this has now been addressed, with all major functionality other than tomography being visible at the "root" of the qinfer module.
