### ISSUE TITLE
Make underlying_model a property of abstract_models.Model whose value is self

### ISSUE THREAD

**Issue by ihincks** [QInfer/python-qinfer#22]
One problem that I have run into several times is trying to access some property of a model hidden under a couple layers of derived/parallel models, but not knowing exacty how many layers deep I need to go because I am trying to keep my code general. This could be solved, I think, by adding the base case described in this issues' title; each model points to a model underneath until it reaches the bottom.

**Comment by scasagrande** [comment]
Did this get resolved in that commit way back in 2014?

**Comment by cgranade** [comment]
Mostly, yes. Since that was a while ago, I'd like to refresh my memory and make sure all of the models which decorate other models correctly inherit from ``DerivedModel`` before closing the issue.

**Comment by ihincks** [comment]
At the moment I think ``ALEApproximateModel`` is the only one that should perhaps be a ``DerivedModel``?

**Comment by cgranade** [comment]
Good point, I think ``ALEApproximateModel`` probably should be a concrete subclass of ``DerivedModel`` as you suggest. I'll start a PR on that.

**Comment by cgranade** [comment]
Resolved by merging #90.
