### ISSUE TITLE
SMCUpdaterBCRB Should Have Properties for current_bim and adaptive_bim

### ISSUE THREAD

**Issue by whitewhim2718** [QInfer/python-qinfer#41]
relevant variables are difficult to find in [SMCUpdaterBCRB](https://github.com/QInfer/python-qinfer/blob/master/src/qinfer/smc.py), and understand how to use without digging through the source code if they are only class variables. Making them properties would allow documentation and better readability. 

        # Before we update, we need to commit the new Bayesian information
        # matrix corresponding to the measurement we just made.
        self.current_bim += self.prior_bayes_information(expparams)[:, :, 0]
        
        # If we're tracking the information content accessible to adaptive
        # algorithms, then we must use the current posterior as the prior
        # for the next step, then add that accordingly.
        if self._track_adaptive:
            self.adaptive_bim += self.posterior_bayes_information(expparams)[:, :, 0]
        
        # We now can update as normal.
        SMCUpdater.update(self, outcome, expparams)

If you think this is a problem, I can fix and submit a PR

-Thomas

**Comment by whitewhim2718** [comment]
Also current the bim update behavior is a plus = on the class adaptive_bim variables. See
`self.adaptive_bim += self.posterior_bayes_information(expparams)[:, :, 0]`
If one calls the variable to gain access to the adaptive(current)_bim of the updater the numpy array is returned. When another update is called, the numpy array that was previously returned will be updated, and the data will be changed. This can lead to unforeseen bugs as it is kind of counter-intuitive. By making these variables into properties, this issue could be solved by returning a copy of a hidden `self._adaptive_bim`.

**Comment by cgranade** [comment]
I think these are good suggestions for improvement, thank you! Though Sphinx allows annotating class variables with ``#:`` comments, avoiding magic comments is always a good idea when possible, such that I agree that it makes a lot of sense to make ``current_bim`` and ``adaptive_bim`` properties with docstrings. I also agree that it makes sense for the new properties to return copies; this is almost surely not going to be the bottleneck in BCRB updating.

**Comment by whitewhim2718** [comment]
Great, I will branch and make these changes and submit a PR later today.

**Comment by cgranade** [comment]
This should now be fixed with #46 being merged. Thanks!
