### ISSUE TITLE
Resample forces particle weights to uniform

### ISSUE THREAD

**Issue by whitewhim2718** [QInfer/python-qinfer#72]
In [smc.py](https://github.com/QInfer/python-qinfer/blob/master/src/qinfer/smc.py) in the _resample_ function new particles, and weights are requested from the resampler. However, several lines down the new weights are set to be uniform. This behaviour seems undesirable as the author of new resampler would expect their returned weights would become the new updater weights. For example Liu-West Resampler should just return the uniform weights itself. 

        self.particle_weights, self.particle_locations = \
            self.resampler(self.model, self.particle_weights, self.particle_locations)

        # Possibly canonicalize, if we've been asked to do so.
        if self._canonicalize:
            self.particle_locations[:, :] = self.model.canonicalize(self.particle_locations)

        # Reset the weights to uniform.
        self.particle_weights[:] = (1/self.n_particles)

I will submit a small patch removing the above line.

**Comment by cgranade** [comment]
I believe this is now fixed with merging in #73.
