### ISSUE TITLE
Parallel serial threshold incorrect

### ISSUE THREAD

**Issue by ihincks** [QInfer/python-qinfer#76]
I would just submit a PR, but am a bit confused about which branch to do it on at this point. Anyway, around line 180 of `parallel.py`, it should be index 0 I think:

    if modelparams.shape[*0*] <= self._serial_threshold:

(also fix theshold typo while at it)

**Comment by ihincks** [comment]
Note to self: don't forget to mention `dview.use_dill()` to deal with models that might have closures.

**Comment by cgranade** [comment]
This should be resolved by #82?

**Comment by ihincks** [comment]
Yep, thanks.
