### ISSUE TITLE
Region estimation troubles

### ISSUE THREAD

**Issue by ihincks** [QInfer/python-qinfer#83]
This applies to the two methods ``region_est_hull`` and ``regioun_est_ellipsoid`` in ``SMCUpdater``.

I get a generic ``Qhull`` error when I try to do it.

If you check out the [documentation for ``Delaunay`` triangulation](http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.spatial.Delaunay.html), you can see there is some kind of switch for ``ndim>4`` in terms of passing arguments to the ``qhull`` C++ library.

**Comment by ihincks** [comment]
Ah, false alarm, this turned out to be my problem. My fifth model parameter happened to be almost exactly 0 for every particle and Dalaunay triangulation doesn't like this. Confusingly, this dimension just happened to coincide with the argument switch in ``qhull``.

**Comment by ihincks** [comment]
Different but related (and hopefully real) problem: ``region_est_hull`` seems to assume 3 dimensions. In particular, in the lines 

    for ia, ib, ic in hull:
        faces.append(points[[ia, ib, ic]]) 

``hull`` is a list of indices of the original points specifying the exterior simplices of the convex hull. For example, if there are 3 dimensions (model parameters), then the external simplices will be triangles, and if there are 4 dimensions, the external simplices will be tetrahedra, etc. In this snippet, ``ia, ib, ic`` therefore correspond to the corners of the triangles on the exterior of the convex hull. If the number of model parameters is different than 3, this doesn't make sense. (This is easy to fix, just want to make sure I understand).

Moreover, there is a warning "Computing convex hulls via the Delaunay triangulation is inefficient and subject to increased numerical instability. Use ConvexHull instead." on the [doc page](http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.spatial.Delaunay.convex_hull.html#scipy.spatial.Delaunay.convex_hull). So I propose moving to ``ConvexHull``, which should be easy and do the same thing.

**Comment by csferrie** [comment]
Yes, this is a real issue. I only implemented it for some plotting purposes on qubit states. If it works for more than 3 dimensions, that would be quite nice.

**Comment by cgranade** [comment]
I think that the ``scipy.spatial.ConvexHull`` class is new as of late 2013, right after @csferrie originally added the ``region_est_hull`` method. We'll take a crack at moving things over to the new class, then, as I think that makes a lot of sense to use.

**Comment by ihincks** [comment]
I'm almost done the required changes, here, will submit a PR sometime.

**Comment by cgranade** [comment]
Ah, I didn't realize, sorry. I'm guessing #87 is redundant then, sorry.

**Comment by ihincks** [comment]
Oh, you are so quick :). So I also added param_slice, but I added it to all three methods in that section. I also added ``in_credible_region`` (pun intended) that works with both the convex hull and the enclosing ellipsoid. So I think our stuff will be compatible. Maybe I will just PR to your branch or something.

**Comment by cgranade** [comment]
Resolved by merging #84 and #86.
