### ISSUE TITLE
Feature: return status

### ISSUE THREAD

**Issue by ihincks** [QInfer/python-qinfer#88]
I am running SMC (with separate `SMCUpdater`s) on lots of independent data sets in a loop. Some of them run into problems (``n_ess`` is smaller than ``10``). It would be nice if the updater carried an attribute that flagged this sort of behaviour so that one doesn't have to manually wade through stdout and see which ones had warnings.

This could be fancy (new updater status class or something), or just a bool, ``no_problems=True``. I'm okay with either.

**Comment by cgranade** [comment]
I think the most natural way to do this is to formalize the logic @csferrie and I used in our recent tomography paper, providing a ``min_n_ess`` property to ``SMCUpdater`` that always returns the smallest effective sample size it has seen thus far.

**Comment by ihincks** [comment]
Yup, that would work for me.

**Comment by cgranade** [comment]
Sounds good, once I get the CI integration finished in #87, then, I'll go on and draft a PR for such a new property.

**Comment by cgranade** [comment]
Resolved by merging #89.
