### ISSUE TITLE
Old Distributions

### ISSUE THREAD

**Issue by ihincks** [QInfer/python-qinfer#99]
There are a couple of distributions in ``qinfer/distributions.py`` that I think have been superceded by new ones in ``qinfer/tomography/distributions.py`` and should be deprecated:

 - ``HaarUniform`` 
 - ``GinibreUniform``
 - ``HilbertSchmidtUniform``

**Comment by ihincks** [comment]
Also, I think ``MVUniformDistribution`` has a confusing name. I think maybe it should eventually just be replaced with a more general Dirichlet distribution.

**Comment by cgranade** [comment]
I agree, and will PR soon to mark those as deprecated. I also think it makes sense, in light of your point about ``MVUniformDistribution`` having a confusing name to deprecate that as well, pending a better named or more general class.

**Comment by ihincks** [comment]
Thanks. The PR could also include a link between the tomography.distributions and distributions in the API docs.

**Comment by cgranade** [comment]
That's a good suggestion, I'll add that as well.
